name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Rsync files to server
        run: |
          rsync -avz --delete \
            --exclude='.git*' \
            --exclude='node_modules' \
            --exclude='.github' \
            --exclude='.vscode' \
            --exclude='github_actions' \
            --exclude='github_actions_pub' \
            ./ user_imperium@209.126.4.141:/www/wwwroot/imperium.cafecauca.com